name: SRC workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: codecov coverage
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: python3 -m pytest --cov=src --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}